---
# file: install-complete.yml

- name: Check and configure compute nodes
  hosts: workers
  gather_facts: no
  any_errors_fatal: true
  serial:
  - 1
  roles:
  - nodes-config

- name: Install and Customize OCP
  hosts: bastion[0]
  roles:
  - ocp-install
  - ocp-customization
  vars:
    worker_count: "{{ groups['workers'] | default([]) | length }}"

- name: OCP post-install HA
  hosts: bastion[1:]
  roles:
  - ocp-ha
  vars:
    bastion_master: "{{ groups['bastion'][0] }}"
